Obstacles:
  - left_pos:
      - -10
      - -10
    length: 10
    width: 2
    height: 2

  - left_pos:
      - -10
      - -8
    length: 2
    width: 8
    height: 2

  - left_pos:
      - -8
      - -2
    length: 6
    width: 2
    height: 2

  - left_pos:
      - -2
      - -8
    length: 2
    width: 8
    height: 2

  - left_pos:
      - 1
      - 2
    length: 2
    width: 4
    height: 5

  - left_pos:
      - 6
      - 2
    length: 4
    width: 2
    height: 5